autonomy_api:
# ROS_DOMAIN_ID=95
  topics:
    -
      topic: /cpr_autonomy_api/$(optenv CLEARPATH_API_VERSION v1_3)/$(env HOSTNAME_ROS_SANITIZED)/appliance/pallet_pose
      type: geometry_msgs/msg/Pose2D
      queue_size: 1
    -
      topic: /cpr_autonomy_api/$(optenv CLEARPATH_API_VERSION v1_3)/$(env HOSTNAME_ROS_SANITIZED)/audio_indication/volume
      type: onboard_systems_msgs/msg/AudioVolume
      queue_size: 1
    -
      topic: /cpr_autonomy_api/$(optenv CLEARPATH_API_VERSION v1_3)/$(env HOSTNAME_ROS_SANITIZED)/bms/battery_status
      type: sensor_msgs/msg/BatteryState
      queue_size: 1
    -
      topic: /cpr_autonomy_api/$(optenv CLEARPATH_API_VERSION v1_3)/$(env HOSTNAME_ROS_SANITIZED)/clouds/scan_points
      type: geometry_extra_msgs/msg/PointVectorVector
      queue_size: 1
    -
      topic: /cpr_autonomy_api/$(optenv CLEARPATH_API_VERSION v1_3)/$(env HOSTNAME_ROS_SANITIZED)/configuration/properties
      type: configuration_msgs/msg/RobotPropertyArray
      queue_size: 1
    -
      topic: /cpr_autonomy_api/$(optenv CLEARPATH_API_VERSION v1_3)/$(env HOSTNAME_ROS_SANITIZED)/configuration/system_id
      type: configuration_msgs/msg/SystemId
      queue_size: 1
    -
      topic: /cpr_autonomy_api/$(optenv CLEARPATH_API_VERSION v1_3)/$(env HOSTNAME_ROS_SANITIZED)/control_selection/control_state
      type: command_control_msgs/msg/ControlSelectionState
      queue_size: 1
    -
      topic: /cpr_autonomy_api/$(optenv CLEARPATH_API_VERSION v1_3)/$(env HOSTNAME_ROS_SANITIZED)/control_selection/current_mode
      type: command_control_msgs/msg/NavigationMode
      queue_size: 1
    -
      topic: /cpr_autonomy_api/$(optenv CLEARPATH_API_VERSION v1_3)/$(env HOSTNAME_ROS_SANITIZED)/diagnostics/diagnostics_aggregated
      type: diagnostic_msgs/msg/DiagnosticArray
      queue_size: 1
    -
      topic: /cpr_autonomy_api/$(optenv CLEARPATH_API_VERSION v1_3)/$(env HOSTNAME_ROS_SANITIZED)/diagnostics/diagnostics_filtered
      type: diagnostic_msgs/msg/DiagnosticArray
      queue_size: 1
    -
      topic: /cpr_autonomy_api/$(optenv CLEARPATH_API_VERSION v1_3)/$(env HOSTNAME_ROS_SANITIZED)/graph/eraser_polygon
      type: geometry_extra_msgs/msg/EraserPolygon
      queue_size: 1
    -
      topic: /cpr_autonomy_api/$(optenv CLEARPATH_API_VERSION v1_3)/$(env HOSTNAME_ROS_SANITIZED)/graph/eraser_progress
      type: std_msgs/msg/Float32
      queue_size: 1
    -
      topic: /cpr_autonomy_api/$(optenv CLEARPATH_API_VERSION v1_3)/$(env HOSTNAME_ROS_SANITIZED)/graph/get_map_progress
      type: std_msgs/msg/Float32
      queue_size: 1
    -
      topic: /cpr_autonomy_api/$(optenv CLEARPATH_API_VERSION v1_3)/$(env HOSTNAME_ROS_SANITIZED)/map_data/robot_active_map
      type: std_msgs/msg/String
      queue_size: 1
    -
      topic: /cpr_autonomy_api/$(optenv CLEARPATH_API_VERSION v1_3)/$(env HOSTNAME_ROS_SANITIZED)/mission/current_job_id
      type: std_msgs/msg/String
      queue_size: 1
    -
      topic: /cpr_autonomy_api/$(optenv CLEARPATH_API_VERSION v1_3)/$(env HOSTNAME_ROS_SANITIZED)/mission/current_step
      type: command_control_msgs/msg/Step
      queue_size: 1
    -
      topic: /cpr_autonomy_api/$(optenv CLEARPATH_API_VERSION v1_3)/$(env HOSTNAME_ROS_SANITIZED)/navigation/active_autonomy_data
      type: perception_navigation_msgs/msg/ActiveAutonomyData
      queue_size: 1
    -
      topic: /cpr_autonomy_api/$(optenv CLEARPATH_API_VERSION v1_3)/$(env HOSTNAME_ROS_SANITIZED)/navigation/current_footprint_mode
      type: std_msgs/msg/String
      queue_size: 1
    -
      topic: /cpr_autonomy_api/$(optenv CLEARPATH_API_VERSION v1_3)/$(env HOSTNAME_ROS_SANITIZED)/navigation/farsight_uplink
      type: perception_navigation_msgs/msg/FarsightList2
      queue_size: 1
    -
      topic: /cpr_autonomy_api/$(optenv CLEARPATH_API_VERSION v1_3)/$(env HOSTNAME_ROS_SANITIZED)/navigation/landmarks_2d
      type: perception_navigation_msgs/msg/Landmarks2D
      queue_size: 1
    -
      topic: /cpr_autonomy_api/$(optenv CLEARPATH_API_VERSION v1_3)/$(env HOSTNAME_ROS_SANITIZED)/navigation/motion_state
      type: perception_navigation_msgs/msg/MotionState
      queue_size: 1
    -
      topic: /cpr_autonomy_api/$(optenv CLEARPATH_API_VERSION v1_3)/$(env HOSTNAME_ROS_SANITIZED)/navigation/odom_intent
      type: perception_navigation_msgs/msg/OdomIntent
      queue_size: 1
    -
      topic: /cpr_autonomy_api/$(optenv CLEARPATH_API_VERSION v1_3)/$(env HOSTNAME_ROS_SANITIZED)/navigation/path_2d
      type: geometry_extra_msgs/msg/Pose2DArray
      queue_size: 1
    -
      topic: /cpr_autonomy_api/$(optenv CLEARPATH_API_VERSION v1_3)/$(env HOSTNAME_ROS_SANITIZED)/navigation/state
      type: perception_navigation_msgs/msg/RobotState
      queue_size: 1
    -
      topic: /cpr_autonomy_api/$(optenv CLEARPATH_API_VERSION v1_3)/$(env HOSTNAME_ROS_SANITIZED)/onboard_systems/wireless_connection
      type: onboard_systems_msgs/msg/WirelessConnection
      queue_size: 1
    -
      topic: /cpr_autonomy_api/$(optenv CLEARPATH_API_VERSION v1_3)/$(env HOSTNAME_ROS_SANITIZED)/robot_insight/footprints_atlas
      type: perception_navigation_msgs/msg/FootprintArray
      queue_size: 1
    -
      topic: /cpr_autonomy_api/$(optenv CLEARPATH_API_VERSION v1_3)/$(env HOSTNAME_ROS_SANITIZED)/robot_state/state_sources
      type: command_control_msgs/msg/SourcesList
      queue_size: 1
    -
      topic: /cpr_autonomy_api/$(optenv CLEARPATH_API_VERSION v1_3)/$(env HOSTNAME_ROS_SANITIZED)/safety/current_mode
      type: std_msgs/msg/UInt8
      queue_size: 1
    -
      topic: /cpr_autonomy_api/$(optenv CLEARPATH_API_VERSION v1_3)/$(env HOSTNAME_ROS_SANITIZED)/slam/current_mode
      type: perception_navigation_msgs/msg/SLAMMode
      queue_size: 1
    -
      topic: /cpr_autonomy_api/$(optenv CLEARPATH_API_VERSION v1_3)/$(env HOSTNAME_ROS_SANITIZED)/slam/graph_lines
      type: geometry_extra_msgs/msg/PointVectorVector
      queue_size: 1
    -
      topic: /cpr_autonomy_api/$(optenv CLEARPATH_API_VERSION v1_3)/$(env HOSTNAME_ROS_SANITIZED)/slam/magnetic_lines
      type: geometry_extra_msgs/msg/PointVectorVector
      queue_size: 1
    -
      topic: /cpr_autonomy_api/$(optenv CLEARPATH_API_VERSION v1_3)/$(env HOSTNAME_ROS_SANITIZED)/slam/scan_match_score
      type: std_msgs/msg/Float64
      queue_size: 1
    -
      topic: /cpr_autonomy_api/$(optenv CLEARPATH_API_VERSION v1_3)/$(env HOSTNAME_ROS_SANITIZED)/slam/scan_points
      type: geometry_extra_msgs/msg/PointVectorVector
      queue_size: 1
    -
      topic: /$(env HOSTNAME_ROS_SANITIZED)/clearpath_api/info
      type: clearpath_api/msg/ApiInfo
      queue_size: 1

  services_1_to_2: []
  services_2_to_1: []
